owner: Starshards789
repo: up

sites:
  - name: HK FRP Server
    url: http://38.76.165.23:26629
    maxResponseTime: 5000

  - name: PVE Hermes SSH
    check: "tcp-ping"
    url: 38.76.165.23
    port: 26700
    maxResponseTime: 5000

  - name: FRPC Panel
    check: "tcp-ping"
    url: 38.76.165.23
    port: 26710
    maxResponseTime: 5000

  - name: Mihomo Panel
    url: http://38.76.165.23:26720
    maxResponseTime: 5000

  - name: Mihomo SOCKS5
    check: "tcp-ping"
    url: 38.76.165.23
    port: 26731
    maxResponseTime: 5000

  - name: WSL2 SSH
    check: "tcp-ping"
    url: 38.76.165.23
    port: 26722
    maxResponseTime: 5000

assignees:
  - Starshards789

status-website:
  baseUrl: /up
  name: "Starshards Status"
  introTitle: "PVE & FRP Monitor"
  introMessage: Real-time service status from outside
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  uptime: "*/5 * * * *"
